services:
  loader1:
    image: capslock/app:local
    build:
      context: .
    container_name: capslock-loader1
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - LOADER_NAME=L1
      - THROTTLE_MS=8000
      - MAX_CALL_DURATION_MS=300000
      - LOOP_SLEEP_US=5000000

  loader2:
    image: capslock/app:local
    build:
      context: .
    container_name: capslock-loader2
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - LOADER_NAME=L2
      - THROTTLE_MS=8000
      - MAX_CALL_DURATION_MS=300000
      - LOOP_SLEEP_US=5000000
  redis:
    image: redis:7
    ports:
      - "6379:6379"
