version: '3.8'
services:
  loader1:
    image: php:8.2-cli
    container_name: capslock-loader1
    working_dir: /app
    volumes:
      - ./:/app:cached
    tty: true
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - LOADER_NAME=L1
      - THROTTLE_MS=200
      - MAX_CALL_DURATION_MS=300000
      - LOOP_SLEEP_US=5000000
    command: ["php", "bin/console", "app:event-loader"]

  loader2:
    image: php:8.2-cli
    container_name: capslock-loader2
    working_dir: /app
    volumes:
      - ./:/app:cached
    tty: true
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - LOADER_NAME=L2
      - THROTTLE_MS=200
      - MAX_CALL_DURATION_MS=300000
      - LOOP_SLEEP_US=5000000
    command: ["php", "bin/console", "app:event-loader"]

  redis:
    image: redis:7
    ports:
      - "6379:6379"
